### ISSUE TITLE
Move to TYPO3-Documentation?

### ISSUE THREAD

**Issue by linawolf** [FriendsOfTYPO3/blog_example#6]
This extension is mainly used in the "[Book Extbase Fluid](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/)"

Currently this one book alone uses Examples from 3 extensions, none of them really up to date most of the time.

There are several issues about this, for example: https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/issues/355

I would like to suggest to move the blog_example extension to the Documentation Team (https://github.com/TYPO3-Documentation) 

This makes it easier for those who work on the documentation to update it. PRs would be automatically announced in Slacks #typo3-docs-review and could be merged by any Documentation Team Merger.

**Comment by sypets** [comment]
@linawolf @franzholz

I think this is a good decision. :thumbsup: I vote to do it.

What I find important though (in addition to this) is to have a dedicated maintainer for this extension and for the book also. It is not just important to clean the example extensions up now, but long term. 

I am for no example extensions rather than outdated extensions. So if - in the future - this is no longer maintained I would vote to remove it. (Which is easier, if it is in the TYPO3-Documentation workspace).

What I also find important is to clean up the book. The last time I looked, the book referred to 3 example extensions.

**Comment by franzholz** [comment]
The blog extension will not be moved for now.  (see comments on slack)
So maybe you should close this issue until another decision is made.

**Comment by sypets** [comment]
+1 for closing.

(after discussion on Slack and talking about it during Slack call).
